"""Text-to-speech tool using Google Gemini API."""

from __future__ import annotations

import base64
import logging
import io
import re
from typing import Any, Dict, Optional, List

try:
    import google.genai as genai
    from google.genai import types
    HAS_GEMINI = True
except ImportError:
    HAS_GEMINI = False

from config import GEMINI_API_KEY

logger = logging.getLogger(__name__)


class GeminiTTSTool:
    """Tool responsible for converting text into audio using Google Gemini TTS."""

    # Available Gemini TTS voices
    AVAILABLE_VOICES = [
        "Puck", "Charon", "Kore", "Fenrir", "Aoede",
        "Leda", "Orus", "Zephyr"
    ]

    def __init__(self) -> None:
        if not HAS_GEMINI:
            logger.warning("google-genai not installed. Install with: pip install google-genai")
            self.client = None
        elif not GEMINI_API_KEY:
            logger.warning("GEMINI_API_KEY not set in environment variables")
            self.client = None
        else:
            self.client = genai.Client(api_key=GEMINI_API_KEY)
            logger.info("Gemini TTS client initialized successfully")

    def _split_into_sentences(self, text: str) -> List[str]:
        """Split text into sentences for processing."""
        # Split on sentence-ending punctuation
        sentences = re.split(r'(?<=[.!?])\s+', text)
        return [s.strip() for s in sentences if s.strip()]

    async def synthesize(
        self,
        text: str,
        voice: str = "Kore",
        output_format: str = "pcm",
        model: Optional[str] = None
    ) -> Dict[str, Any]:
        """Generate speech audio from text using Google Gemini TTS.
        
        Args:
            text: Text to convert to speech
            voice: Voice name (default: Kore)
            output_format: Output format - "pcm" for raw audio, "wav" for wave file
            model: Optional model override
        
        Returns:
            Dict with success, audio_bytes, and optional error
        """
        if not self.client:
            return {
                "success": False,
                "error": "Gemini client not initialized. Check GEMINI_API_KEY.",
                "audio_bytes": None,
            }

        if not text or not text.strip():
            return {
                "success": False,
                "error": "No text provided.",
                "audio_bytes": None,
            }

        try:
            # Validate voice
            if voice not in self.AVAILABLE_VOICES:
                voice = "Kore"  # Default voice
            
            # Use specified model or default TTS model
            tts_model = model or "gemini-2.5-flash-preview-tts"
            
            # Configure speech generation
            speech_config = types.SpeechConfig(
                voice_config=types.VoiceConfig(
                    prebuilt_voice_config=types.PrebuiltVoiceConfig(
                        voice_name=voice
                    )
                )
            )
            
            # Generate speech
            response = self.client.models.generate_content(
                model=tts_model,
                contents=text,
                config=types.GenerateContentConfig(
                    response_modalities=["AUDIO"],
                    speech_config=speech_config
                )
            )
            
            # Extract audio data
            audio_data = None
            if response.candidates and response.candidates[0].content.parts:
                for part in response.candidates[0].content.parts:
                    if hasattr(part, 'inline_data') and part.inline_data:
                        audio_data = part.inline_data.data
                        break
            
            if not audio_data:
                return {
                    "success": False,
                    "error": "No audio generated by Gemini TTS",
                    "audio_bytes": None,
                }
            
            logger.info(f"Gemini TTS successful: {len(audio_data)} bytes")
            return {
                "success": True,
                "audio_bytes": audio_data,
                "format": "pcm",  # Gemini returns raw PCM audio at 24kHz
                "sample_rate": 24000,
            }
            
        except Exception as exc:
            logger.error(f"Gemini TTS failed: {exc}")
            return {
                "success": False,
                "error": str(exc),
                "audio_bytes": None,
            }

    async def synthesize_pcm(
        self,
        text: str,
        voice: str = "Kore",
        model: Optional[str] = None
    ) -> Dict[str, Any]:
        """Generate PCM audio for streaming to Twilio.
        
        Gemini TTS outputs 24kHz PCM which can be converted to mu-law for Twilio.
        """
        return await self.synthesize(text, voice, "pcm", model)
